### ISSUE TITLE
not starting / killing panel when removed

### ISSUE THREAD

**Issue by squalou** [cosmic-utils/minimon-applet#2]
Hi,

I have a curious behavior : when installed, adding it to Panel (or Dock), the applet does not show up.
(the panel blinks to refresh, usual when changing things there, but that's all).

Then when removing it from the list, the whole panel gets blank, nothing displayed.

Could be related to my setup :
- pop 22.04
- cosmic alpha from repo
- minimon applet from .deb (had the same result with 1.3 or 2.0)

**Comment by Hyperchaotic** [comment]
Hi thanks for the report. I ran some tests in some VMs.

It works on Pop!_OS 24.04 Alpha, without or with popdev:master.
I see the reported behaviour on Pop!_OS 22.

I built a package on Pop!_OS 22.04, would you mind trying it out?

[cosmic-applet-minimon_POP-22.04_0.2.0_amd64.deb.zip](https://github.com/user-attachments/files/16650208/cosmic-applet-minimon_POP-22.04_0.2.0_amd64.deb.zip)

**Comment by squalou** [comment]
it works !

thank you so much.

IMHO : I can stick to this version waiting for 24.04 to be released, no need to bother packaging any other potential future version.
