### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Department-stack** [cosmic-utils/minimon-applet#7]
Is it possible to have 2 minimon-applet's on the same panel? I would have to have the applet displaying ram on the left of the clock. And the applet displaying cpu usage to the right of the clock.

**Comment by Hyperchaotic** [comment]
Not as it is, I'm guessing it could be done by rebuilding as a new applet with a different Name in Cargo.toml and different "id" tag in metadata.xml and APP_IDs in app.rs, so it appears as a different app and stores settings separately from the other instance using different APP_IDs.
